apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}

data:

  SPRING_PROFILES_ACTIVE: "{{ .Values.config.SPRING_PROFILES_ACTIVE }}"

  DB_HOST: "{{ .Values.config.DB_HOST }}"

  DB_PORT: "{{ .Values.config.DB_PORT }}"

  DB_NAME: "{{ .Values.config.DB_NAME }}"