apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: backend

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          envFrom:
            - configMapRef:
                name: {{ include "backend.fullname" . }}

          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.springDatasource.url | quote }}

            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.springDatasource.username | quote }}

            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.springDatasource.password | quote }}  
              
                 
          # Temporary: Disable Key Vault CSI Mount
          # volumeMounts:
          #   - name: secrets-store
          #     mountPath: "/mnt/secrets-store"
          #     readOnly: true

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}

            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.containerPort }}

            initialDelaySeconds: 30
            periodSeconds: 20

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.containerPort }}

            initialDelaySeconds: 15
            periodSeconds: 10

      # Temporary: Disable Key Vault CSI Volume
      # volumes:
      #   - name: secrets-store
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #
      #       volumeAttributes:
      #         secretProviderClass: {{ include "backend.fullname" . }}-spc