{{- if .Values.ingress.enabled }}

apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  rules:
    - host: {{ (index .Values.ingress.hosts 0).host }}
      http:
        paths:
          - path: {{ (index .Values.ingress.hosts 0).path }}
            pathType: {{ (index .Values.ingress.hosts 0).pathType }}
            backend:
              service:
                name: {{ include "frontend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

{{- end }}